/**
 * Write the encoded surfaces out as a TypeScript module, so the demo imports them instead of fetching.
 *
 * The stream goes in as base64 rather than as a number array for a measured reason: the same data as a
 * plain literal is about ten times the source size, and the browser has `atob` built in.
 */
import { readFileSync, writeFileSync, statSync } from 'node:fs';

const LEVEL = process.argv[2] ?? 'x2';
const tag = LEVEL === 'default' ? '-default' : `-${LEVEL}`;
const DEST = process.argv[3] ?? 'src/demos/girl-character/surfaceData.ts';
const CODEC_IMPORT = process.env.CHARACTER_CODEC_IMPORT ?? './surfaceCodec';

// PACKAGED (v1.5.1): must match CHARACTER_WORK_TAG used when encode_surfaces.mjs wrote these files.
const workTag = process.env.CHARACTER_WORK_TAG ?? '';
const meta = JSON.parse(readFileSync(`work/surfaces${workTag}${tag}.json`, 'utf8'));
const base64 = readFileSync(`work/surfaces${workTag}${tag}.b64`, 'utf8').trim();

const nodes = meta.nodes.map((n) => ({
  node: n.node,
  region: n.region,
  material: n.material ?? null,
  cellMillimetres: n.cellMillimetres,
  vertexCount: n.vertexCount,
  origin: n.origin,
  dims: n.dims,
  bytes: n.bytes,
  exceptionQuads: n.exceptionQuads,
}));
const vertices = nodes.reduce((sum, n) => sum + n.vertexCount, 0);
const exceptions = nodes.reduce((sum, n) => sum + n.exceptionQuads, 0);

const header = `import type { EncodedNode } from '${CODEC_IMPORT}';

/**
 * GENERATED by scripts/emit_surface_module.mjs -- do not edit by hand.
 *
 * The figure's implicit surfaces, encoded as described in surfaceCodec.ts and carried IN THE BUNDLE so
 * that nothing is fetched at runtime. Regenerate with:
 *
 *     node scripts/encode_surfaces.mjs ${LEVEL}
 *     node scripts/emit_surface_module.mjs ${LEVEL}
 *
 * Measured, on the level shipped here:
 *
 *     detail level          ${LEVEL}
 *     nodes                 ${nodes.length}
 *     vertices              ${vertices.toLocaleString()}
 *     bytes per vertex      ${(Buffer.from(base64, 'base64').length / vertices).toFixed(2)}
 *     stream                ${(Buffer.from(base64, 'base64').length / 1e6).toFixed(2)} MB
 *     base64 in this file   ${(base64.length / 1e6).toFixed(2)} MB
 *     exception quads       ${exceptions}
 *
 * Round-tripped against the source before being written: identical vertex and triangle counts,
 * identical colours, positions inside the quantisation step. See scripts/verify_roundtrip.mjs.
 */
export const SURFACE_LEVEL = ${JSON.stringify(LEVEL)};

export const SURFACE_NODES: readonly EncodedNode[] = ${JSON.stringify(nodes, null, 2)};

export const SURFACE_STREAM =
  '${base64}';
`;
writeFileSync(DEST, header);
console.log(`wrote ${DEST}  ${(statSync(DEST).size / 1e6).toFixed(2)} MB`
  + `  (${nodes.length} nodes, ${vertices.toLocaleString()} vertices, ${exceptions} exception quads)`);
