"""Stage R5 runtime emitter: clip list -> standalone TypeScript animation runtime.

Turns a list of already-identified/authored clips (Stage R3/R4 output — this
module does not classify or author anything) into a self-contained .ts module
that builds the R5 runtime around a three.js `AnimationMixer`: bind-space
setup (R1), ticker collection that survives lazily-built geometry (R5.1),
presentation-offset-vs-animated-pose ordering (R5.2), the play/seek/stop/
advance controller contract (R5.3), and the Gate R1 harness that is the only
check able to tell a clip that plays from a clip that merely exists.

See docs/pipelines/character-rigging-animation-1.5.2.md, Stage R1 and Stage
R5, and forge/stage5_rig/CONTRACT_1.5.2.md for the module boundary this file
must respect (it owns emit_animation_runtime.py and nothing else; it does not
import clip_features.py / skin_conditioning.py / action_design.py / rig_gates.py
— its input is the plain clip-list shape documented below, not their internal
dataclasses).

Pure Python 3.10+ stdlib. No pip installs, no string.Template brace-escaping
footguns — plain token replacement is used instead of str.format()/f-strings
against the TS body, because that body is full of literal `{`/`}` (matches
the idiom in forge/stage5_rig/emit_rig.py).
"""

from __future__ import annotations

import json
from typing import Any, Optional

# Named export per CONTRACT_1.5.2.md's shared numeric conventions: every
# threshold gets a module constant with the spec's name. This is the float32
# epsilon from Stage R1's Gate R1 (docs §"Gate R1 (the one that catches
# silent death)"): `maxSampledBindingDelta <= 2^-23`.
BINDING_EPSILON = 2**-23

# Gate R1 requires seeking each clip to AT LEAST five times ("five poses is
# not coverage" — Stage R6/G10 makes the same point about visual sweeps, and
# Stage R1's own gate description says "seek each clip to five times"). This
# is a floor, not a target: callers may pass more via options, never fewer.
MINIMUM_GATE_R1_SAMPLES = 5

_REQUIRED_CLIP_KEYS = ("id", "label", "sourceName", "duration", "loop")


def _validate_clip(clip: dict[str, Any]) -> None:
    for key in _REQUIRED_CLIP_KEYS:
        if key not in clip:
            raise ValueError(f"clip missing required key '{key}': {clip!r}")
    if clip["loop"] is not None and not isinstance(clip["loop"], bool):
        raise ValueError(
            f"clip '{clip.get('id')}' has loop={clip['loop']!r}; "
            "must be True, False, or None (undecidable/unmeasured)"
        )
    if not isinstance(clip["duration"], (int, float)):
        raise ValueError(f"clip '{clip.get('id')}' has non-numeric duration: {clip['duration']!r}")


_TEMPLATE = r"""// AUTO-GENERATED by forge/stage5_rig/emit_animation_runtime.py — Stage R5 runtime.
// Do not hand-edit; regenerate from the clip list instead.
import * as THREE from 'three';

// ---------------------------------------------------------------------------
// Clip data. `loop: null` means Stage R3/R4 could not measure poseReturn
// (see docs/pipelines/character-rigging-animation-1.5.2.md §"loop rule") —
// it is NOT a synonym for `false`, and resolveLoopMode() below never treats
// it as LoopRepeat either. Labels/sourceNames are attacker-adjacent free
// text (JSON-escaped below); mountAnimationUI() renders them via
// `textContent`, never `innerHTML`.
// ---------------------------------------------------------------------------
export interface ClipInfo {
  id: string;
  label: string;
  sourceName: string;
  duration: number;
  loop: boolean | null;
}

export const CLIPS: ClipInfo[] = __CLIPS_JSON__;

// Stage R1 Gate R1 float32 epsilon: `maxSampledBindingDelta <= 2 ** -23`.
export const BINDING_EPSILON = 2 ** -23;

export interface LoopMode {
  mode: THREE.AnimationActionLoopStyles;
  repetitions: number;
  clampWhenFinished: boolean;
}

/**
 * Loop mode comes from the MEASURED `loop` flag, never from a guess:
 *   loop === true   -> LoopRepeat, Infinity
 *   loop === false  -> LoopOnce, 1, clampWhenFinished = true
 *   loop === null   -> LoopOnce, 1, clampWhenFinished = true, AND loop was
 *                       not measured for this clip (poseReturn unmeasured /
 *                       undecidable) — never silently upgraded to
 *                       LoopRepeat just because that would look nicer.
 */
export function resolveLoopMode(clip: ClipInfo): LoopMode {
  if (clip.loop === true) {
    return { mode: THREE.LoopRepeat, repetitions: Infinity, clampWhenFinished: false };
  }
  if (clip.loop === false) {
    return { mode: THREE.LoopOnce, repetitions: 1, clampWhenFinished: true };
  }
  // clip.loop === null: loop was not measured for this clip. Play once and
  // clamp rather than assume it can repeat seamlessly.
  return { mode: THREE.LoopOnce, repetitions: 1, clampWhenFinished: true };
}

// ---------------------------------------------------------------------------
// Stage R1 -- Bind space. THE RULE THAT CAUSED EVERY RIGGING FAILURE IN 1.5.1.
//
// three.js SkinnedMesh defaults to AttachedBindMode, in which
// bindMatrixInverse is recomputed from the mesh's matrixWorld on every
// updateMatrixWorld, so the skinning evaluation is
//   v' = skinMatrix * bindMatrix * v          // matrixWorld cancels out
// entirely. Three things were tried before the one below, each measured:
//   1. mesh.bind(skeleton, armature.matrixWorld)                    -> a
//      blank frame (the bind was applied twice).
//   2. identity bind + a `skinSpace` wrapper transform               -> the
//      figure rendered 0.5 m high and floating.
//   3. identity bind + the armature's translation folded into the
//      display offset                                                -> the
//      figure rendered offset by exactly that armature translation, because
//      the armature's transform is already inside skinMatrix and adding it
//      again double-counts it.
// The rule: bind at identity, ALWAYS, and derive the display offset from the
// mesh's own bounds — never from the armature.
// ---------------------------------------------------------------------------
export function computeDisplayOffset(mesh: THREE.SkinnedMesh): THREE.Vector3 {
  mesh.geometry.computeBoundingBox();
  const bounds = mesh.geometry.boundingBox as THREE.Box3;
  const centre = new THREE.Vector3();
  bounds.getCenter(centre);
  // Bounds-only, by construction: (-centre.x, -min.y, -centre.z) seats the
  // figure on Y = 0. No armature transform is read here, ever.
  return new THREE.Vector3(-centre.x, -bounds.min.y, -centre.z);
}

export function bindAtIdentity(mesh: THREE.SkinnedMesh, skeleton: THREE.Skeleton, group: THREE.Object3D): void {
  mesh.bind(skeleton, new THREE.Matrix4());   // identity, always, in attached mode
  group.position.copy(computeDisplayOffset(mesh));   // presentation only
}

// ---------------------------------------------------------------------------
// Stage R5.1 -- ticker collection vs lazy geometry.
//
// A viewer that walks the scene once at start() collecting userData.tick
// MISSES every demo whose rig arrives later: the mixer holds the action,
// nothing calls mixer.update, every clip plays silently. refreshTickers()
// must be callable again, any time, and onCharacterReady() is the wiring a
// lazily-built character calls when its payload resolves.
// ---------------------------------------------------------------------------
export type Tick = (dt: number, elapsed: number) => void;

let tickers: Tick[] = [];

export function refreshTickers(scene: THREE.Object3D): void {
  tickers = [];
  scene.traverse((node) => {
    const tick = (node.userData as { tick?: Tick }).tick;
    if (typeof tick === 'function') {
      tickers.push(tick);
    }
  });
}

/** Call when a lazily-built character's rig/geometry payload resolves. */
export function onCharacterReady(scene: THREE.Object3D): void {
  refreshTickers(scene);
}

// ---------------------------------------------------------------------------
// Stage R5.2 -- presentation offsets vs animated pose.
//
// If the viewer offsets parts for an explode/inspect view, it must subtract
// the offset it applied last frame BEFORE the rig ticks, and re-apply it
// AFTER. Never restore a cached rest pose here — a cached rest pose
// overwrites whatever the animation just produced.
// ---------------------------------------------------------------------------
let removeExplodeOffsetHook: () => void = () => {};
let applyExplodeOffsetHook: () => void = () => {};

/** Viewer-supplied presentation hooks; both default to no-ops. */
export function setExplodeOffsetHooks(remove: () => void, apply: () => void): void {
  removeExplodeOffsetHook = remove;
  applyExplodeOffsetHook = apply;
}

export function tickAll(dt: number, elapsed: number): void {
  removeExplodeOffsetHook();      // hand the animated transform back
  for (const tick of tickers) {
    tick(dt, elapsed);
  }
  applyExplodeOffsetHook();       // presentation on top
}

// ---------------------------------------------------------------------------
// Stage R5.3 -- controller contract.
//
//   play(name)    stopAllAction -> restore bind pose -> reset -> set loop mode -> play
//   seek(name,t)  as play, then paused = true, time = t, mixer.update(0), updateMatrixWorld(true)
//   stop()        stopAllAction -> restore bind pose -> active = 'idle'
//   advance(dt)   mixer.update(dt) -> updateMatrixWorld(true)
//
// Restoring the bind pose BEFORE each play is what stops clips bleeding into
// one another: a clip that ends mid-pose leaves joints displaced, and the
// next clip's tracks only overwrite the joints they address.
// ---------------------------------------------------------------------------
interface TransformSnapshot {
  position: THREE.Vector3;
  quaternion: THREE.Quaternion;
  scale: THREE.Vector3;
}

export class AnimationController {
  readonly root: THREE.Object3D;
  readonly mixer: THREE.AnimationMixer;
  active: string = 'idle';

  private readonly actions = new Map<string, THREE.AnimationAction>();
  private readonly clipsById = new Map<string, ClipInfo>();
  private readonly bindPose = new Map<THREE.Object3D, TransformSnapshot>();

  constructor(root: THREE.Object3D, animationClips: THREE.AnimationClip[], clipInfos: ClipInfo[]) {
    this.root = root;
    this.mixer = new THREE.AnimationMixer(root);
    this.captureBindPose();
    for (const info of clipInfos) {
      this.clipsById.set(info.id, info);
      const clip = animationClips.find((candidate) => candidate.name === info.id || candidate.name === info.sourceName);
      if (!clip) continue;
      this.actions.set(info.id, this.mixer.clipAction(clip));
    }
  }

  private captureBindPose(): void {
    this.bindPose.clear();
    this.root.traverse((node) => {
      this.bindPose.set(node, {
        position: node.position.clone(),
        quaternion: node.quaternion.clone(),
        scale: node.scale.clone(),
      });
    });
  }

  private restoreBindPose(): void {
    for (const [node, pose] of this.bindPose) {
      node.position.copy(pose.position);
      node.quaternion.copy(pose.quaternion);
      node.scale.copy(pose.scale);
    }
  }

  play(name: string): void {
    this.mixer.stopAllAction();
    this.restoreBindPose();
    const action = this.actions.get(name);
    const info = this.clipsById.get(name);
    if (!action || !info) {
      return;
    }
    action.reset();
    const loopMode = resolveLoopMode(info);
    action.setLoop(loopMode.mode, loopMode.repetitions);
    action.clampWhenFinished = loopMode.clampWhenFinished;
    action.play();
    this.active = name;
  }

  seek(name: string, t: number): void {
    this.play(name);
    const action = this.actions.get(name);
    if (!action) {
      return;
    }
    action.paused = true;
    action.time = t;
    this.mixer.update(0);
    this.root.updateMatrixWorld(true);
  }

  stop(): void {
    this.mixer.stopAllAction();
    this.restoreBindPose();
    this.active = 'idle';
  }

  advance(dt: number): void {
    this.mixer.update(dt);
    this.root.updateMatrixWorld(true);
  }

  getAction(name: string): THREE.AnimationAction | undefined {
    return this.actions.get(name);
  }
}

// ---------------------------------------------------------------------------
// Animation UI — a MOUNT FUNCTION, not a side effect of module load, so it
// can run after the controller exists (Stage R5.1: "Same for the animation
// UI: mount the panel as a function so it can also run after the controller
// exists.").
// ---------------------------------------------------------------------------
export function mountAnimationUI(
  container: HTMLElement,
  controller: AnimationController,
  clips: ClipInfo[] = CLIPS,
): () => void {
  const buttons: HTMLButtonElement[] = [];
  for (const clip of clips) {
    const button = document.createElement('button');
    button.textContent = clip.label;   // textContent only -- never innerHTML
    button.addEventListener('click', () => controller.play(clip.id));
    container.appendChild(button);
    buttons.push(button);
  }
  return function unmountAnimationUI(): void {
    for (const button of buttons) {
      container.removeChild(button);
    }
  };
}

// ---------------------------------------------------------------------------
// Gate R1 -- the ONLY check that distinguishes a clip that PLAYS from a clip
// that merely exists, holds an action, reports a duration and drives
// nothing. Seeks each clip to (at least) __GATE_SAMPLE_COUNT__ evenly spaced
// times and, at each one, compares the actually-bound node transform against
// what the track's own interpolant says it should be.
// ---------------------------------------------------------------------------
export interface GateR1ClipResult {
  clipId: string;
  maxSampledBindingDelta: number;
  sampleTimes: number[];
  passed: boolean;
}

function trackNodeAndProperty(trackName: string): { nodeName: string; property: 'position' | 'quaternion' | 'scale' } {
  const dot = trackName.lastIndexOf('.');
  const nodeName = trackName.slice(0, dot);
  const rawProperty = trackName.slice(dot + 1);
  const property = rawProperty === 'quaternion' || rawProperty === 'scale' ? rawProperty : 'position';
  return { nodeName, property };
}

function readTransformComponent(node: THREE.Object3D, property: 'position' | 'quaternion' | 'scale'): number[] {
  if (property === 'quaternion') {
    return node.quaternion.toArray();
  }
  if (property === 'scale') {
    return node.scale.toArray();
  }
  return node.position.toArray();
}

function maxComponentDelta(actual: number[], expected: ArrayLike<number>): number {
  let max = 0;
  for (let i = 0; i < actual.length; i++) {
    const delta = Math.abs(actual[i] - (expected[i] as number));
    if (delta > max) {
      max = delta;
    }
  }
  return max;
}

export function runGateR1(
  controller: AnimationController,
  animationClips: THREE.AnimationClip[],
  sampleCount: number = __GATE_SAMPLE_COUNT__,
): GateR1ClipResult[] {
  const effectiveSamples = Math.max(__GATE_SAMPLE_COUNT__, sampleCount);
  const results: GateR1ClipResult[] = [];
  for (const clip of animationClips) {
    let maxDelta = 0;
    const sampleTimes: number[] = [];
    for (let i = 0; i < effectiveSamples; i++) {
      const t = effectiveSamples === 1 ? 0 : (clip.duration * i) / (effectiveSamples - 1);
      sampleTimes.push(t);
      controller.seek(clip.name, t);
      for (const track of clip.tracks) {
        const { nodeName, property } = trackNodeAndProperty(track.name);
        const node = controller.root.getObjectByName(nodeName);
        if (!node) {
          continue;
        }
        const interpolant = track.createInterpolant();
        const expected = interpolant.evaluate(t);
        const actual = readTransformComponent(node, property);
        const delta = maxComponentDelta(actual, expected);
        if (delta > maxDelta) {
          maxDelta = delta;
        }
      }
    }
    results.push({
      clipId: clip.name,
      maxSampledBindingDelta: maxDelta,
      sampleTimes,
      passed: maxDelta <= BINDING_EPSILON,
    });
  }
  return results;
}
"""


def emit_animation_runtime(clips: list[dict[str, Any]], options: Optional[dict[str, Any]] = None) -> str:
    """Emit the Stage R5 runtime TypeScript module for `clips`.

    `clips` items carry `id`, `label`, `sourceName`, `duration`, and `loop`
    (`True`/`False`/`None` — `None` means poseReturn was unmeasured /
    undecidable and must be emitted as `LoopOnce` with a comment, never
    silently `LoopRepeat`).

    `options`, all optional:
      - `gate_sample_count` (int, default 5): the default sample count baked
        into `runGateR1`'s signature. Gate R1 (docs §Stage R1) requires
        seeking each clip to AT LEAST five times; values below
        `MINIMUM_GATE_R1_SAMPLES` are rejected, not silently clamped, so a
        caller cannot accidentally under-sample the one gate that catches
        silent binding failure.
    """
    options = options or {}
    for clip in clips:
        _validate_clip(clip)

    gate_sample_count = int(options.get("gate_sample_count", MINIMUM_GATE_R1_SAMPLES))
    if gate_sample_count < MINIMUM_GATE_R1_SAMPLES:
        raise ValueError(
            f"gate_sample_count={gate_sample_count} is below MINIMUM_GATE_R1_SAMPLES="
            f"{MINIMUM_GATE_R1_SAMPLES}; Gate R1 requires seeking each clip at least "
            "five times to be a meaningful check"
        )

    clips_payload = [
        {
            "id": clip["id"],
            "label": clip["label"],
            "sourceName": clip["sourceName"],
            "duration": clip["duration"],
            "loop": clip["loop"],
        }
        for clip in clips
    ]

    replacements = {
        "__CLIPS_JSON__": json.dumps(clips_payload, indent=2),
        "__GATE_SAMPLE_COUNT__": str(gate_sample_count),
    }
    source = _TEMPLATE
    for token, value in replacements.items():
        if token not in source:
            raise AssertionError(f"template token {token} not found — template/replacement drift")
        source = source.replace(token, value)
    return source
